image: fredden/rails-code-review:2.4.1

pipelines:
  default:
    - step:
        script:
          - brakeman -Aqz
          - rubocop --rails
          - rubycritic --format console --minimum-score 80
          - rails_best_practices
